country_list = [
    "Argentina",
    "Australia",
    "Bangladesh",
    "Brazil",
    "Canada",
    "Ghana",
    "India",
    "Indonesia",
    "Ireland",
    "Malaysia",
    "Mexico",
    "New_Zealand",
    "Nigeria",
    "Pakistan",
    "Philippines",
    "Russia",
    "Singapore",
    "South_Africa",
    "Spain",
    "Turkey",
    "England",
    "United_States"
]

file_country_to_country_list = {
    "Argentina": "Argentina",
    "Australia": "Australia",
    "Bangladesh": "Bangladesh",
    "Brazil": "Brazil",
    "Canada": "Canada",
    "Ghana": "Ghana",
    "India": "India",
    "Indonesia": "Indonesia",
    "the_Republic_of_Ireland": "Ireland",
    "Malaysia": "Malaysia",
    "Mexico": "Mexico",
    "New_Zealand": "New_Zealand",
    "Nigeria": "Nigeria",
    "Pakistan": "Pakistan",
    "the_Philippines": "Philippines",
    "Russia": "Russia",
    "Singapore": "Singapore",
    "South_Africa": "South_Africa",
    "Spain": "Spain",
    "Turkey": "Turkey",
    "England": "England",
    "the_United_States": "United_States"
}

country_list_to_file_country = {
    "Argentina": "Argentina",
    "Australia": "Australia",
    "Bangladesh": "Bangladesh",
    "Brazil": "Brazil",
    "Canada": "Canada",
    "Ghana": "Ghana",
    "India": "India",
    "Indonesia": "Indonesia",
    "Ireland": "the_Republic_of_Ireland",
    "Malaysia": "Malaysia",
    "Mexico": "Mexico",
    "New_Zealand": "New_Zealand",
    "Nigeria": "Nigeria",
    "Pakistan": "Pakistan",
    "Philippines": "the_Philippines",
    "Russia": "Russia",
    "Singapore": "Singapore",
    "South_Africa": "South_Africa",
    "Spain": "Spain",
    "Turkey": "Turkey",
    "England": "England",
    "United_States": "the_United_States"
}