
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DATE DAY H2_CLOSE_TAG H2_OPEN_TAG H3_CLOSE_TAG H3_OPEN_TAG MONTH NOBR ON PARA_CLOSE PARA_DATA PARA_START P_CLOSE P_OPEN SPAN_CLOSE SPAN_DATE TB_WORLD TD TD_A TD_CLOSE TD_COUNTRY TD_COUNTRY_SPAN TD_OPEN TD_STRONG TR_CLASS TR_CONTINENT_OPEN YEAR YEAR2\n    start : YEAR\n          | year2\n          | data\n    \n    year2 : YEAR2\n    \n    data : P_OPEN\n    \n    start : DATE PARA_DATA\n    \n    start : continent_data\n          | world_data\n          | country_data\n    \n    continent_data : TR_CONTINENT_OPEN TD TD_OPEN NOBR TD_CLOSE TD TD TD TD TD TD TD TD TD TD TD TD TD\n    \n    world_data : TB_WORLD TR_CLASS TD TD_STRONG TD TD TD TD TD TD TD TD TD TD TD TD\n    \n    country_data : TD_COUNTRY TD TD TD TD TD TD TD TD TD TD TD TD TD\n                 | TD_COUNTRY_SPAN TD TD TD TD TD TD TD TD TD TD TD TD TD\n                 | TD_COUNTRY TD TD TD TD TD TD TD TD TD TD TD TD TD_A\n                 | TD_COUNTRY_SPAN TD TD TD TD TD TD TD TD TD TD TD TD TD_A\n\n    '
    
_lr_action_items = {'YEAR':([0,],[2,]),'DATE':([0,],[5,]),'YEAR2':([0,],[9,]),'P_OPEN':([0,],[10,]),'TR_CONTINENT_OPEN':([0,],[11,]),'TB_WORLD':([0,],[12,]),'TD_COUNTRY':([0,],[13,]),'TD_COUNTRY_SPAN':([0,],[14,]),'$end':([1,2,3,4,6,7,8,9,10,15,66,67,68,69,73,75,],[0,-1,-2,-3,-7,-8,-9,-4,-5,-6,-12,-14,-13,-15,-11,-10,]),'PARA_DATA':([5,],[15,]),'TD':([11,13,14,17,18,19,22,23,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,70,71,72,74,],[16,18,19,21,22,23,26,27,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,68,70,71,72,73,74,75,]),'TR_CLASS':([12,],[17,]),'TD_OPEN':([16,],[20,]),'NOBR':([20,],[24,]),'TD_STRONG':([21,],[25,]),'TD_CLOSE':([24,],[28,]),'TD_A':([62,63,],[67,69,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'start':([0,],[1,]),'year2':([0,],[3,]),'data':([0,],[4,]),'continent_data':([0,],[6,]),'world_data':([0,],[7,]),'country_data':([0,],[8,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('start -> YEAR','start',1,'p_country_news','main.py',104),
  ('start -> year2','start',1,'p_country_news','main.py',105),
  ('start -> data','start',1,'p_country_news','main.py',106),
  ('year2 -> YEAR2','year2',1,'p_year2','main.py',113),
  ('data -> P_OPEN','data',1,'p_data','main.py',120),
  ('start -> DATE PARA_DATA','start',2,'p_covid_news','main.py',129),
  ('start -> continent_data','start',1,'p_start','main.py',136),
  ('start -> world_data','start',1,'p_start','main.py',137),
  ('start -> country_data','start',1,'p_start','main.py',138),
  ('continent_data -> TR_CONTINENT_OPEN TD TD_OPEN NOBR TD_CLOSE TD TD TD TD TD TD TD TD TD TD TD TD TD','continent_data',18,'p_continents','main.py',144),
  ('world_data -> TB_WORLD TR_CLASS TD TD_STRONG TD TD TD TD TD TD TD TD TD TD TD TD','world_data',16,'p_world','main.py',153),
  ('country_data -> TD_COUNTRY TD TD TD TD TD TD TD TD TD TD TD TD TD','country_data',14,'p_countries','main.py',161),
  ('country_data -> TD_COUNTRY_SPAN TD TD TD TD TD TD TD TD TD TD TD TD TD','country_data',14,'p_countries','main.py',162),
  ('country_data -> TD_COUNTRY TD TD TD TD TD TD TD TD TD TD TD TD TD_A','country_data',14,'p_countries','main.py',163),
  ('country_data -> TD_COUNTRY_SPAN TD TD TD TD TD TD TD TD TD TD TD TD TD_A','country_data',14,'p_countries','main.py',164),
]
